export const Commands = {
    PickFolder: 'pickFolder',
    OpenFolder: 'openFolder',
    LoadRecentWorkspaces: 'loadRecentWorkspaces',
    OpenRecentWorkspace: 'openRecentWorkspace',
    OpenWorkspace: 'openWorkspace',
    CreateWorkspace: 'createWorkspace',
    LoadChallenges: 'loadChallenges',
    CreateChallenge: 'createChallenge',
    UpdateChallenge: 'updateChallenge',
    DeleteChallenge: 'deleteChallenge',
    CreateReadme: 'createReadme',
    AddAttachments: 'addAttachments',
    ReorderChallenges: 'reorderChallenges',
    UpdateDiscordRPC: 'updateDiscordRPC',
    GetAttachment: 'getAttachment',
    SaveAttachment: 'saveAttachment',
    DeleteAttachment: 'deleteAttachment',
    GetTools: 'getTools',
    ExecuteTool: 'executeTool',
    OpenInstallTerminal: 'openInstallTerminal',
    ExtractZip: 'extractZip'
} as const
